const releases=[
  {"status": "Accepted", 
  "stats": 
      {"community": 
          {"in_collection": 310, 
          "in_wantlist": 1231}}, 
      "thumb": "", 
      "title": "Kaos", 
      "format": "10\"", 
      "label": "Svek", 
      "role": "Main", 
      "year": 1997, 
      "resource_url": "https://img.discogs.com/1SnBs9zztjQomodblW4yynMBikg=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-9121553-1475148661-7202.jpeg.jpg", 
      "artist": "Stephan-G* & The Persuader", 
      "type": "release", 
      "id": 20209}, 
  {"status": "Accepted", 
  "stats": 
      {"community": 
          {"in_collection": 525, 
          "in_wantlist": 645}}, 
      "thumb": "", 
      "title": "Snorkelmannen \u00d8 Hans V\u00e4nner", 
      "format": "12\"", 
      "label": "Svek", 
      "role": "Main", 
      "year": 1997, 
      "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
      "artist": "Mr. Barth* & The Persuader", 
      "type": "release", 
      "id": 62584}, 
  {"stats": 
      {"community": 
          {"in_collection": 400, 
          "in_wantlist": 592}}, 
      "thumb": "", 
      "artist": "The Persuader", 
      "main_release": 4664, 
      "title": "Stockholm By Night", 
      "role": "Main", 
      "year": 1997, 
      "resource_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXP05me80mcWKN5wijCvhdAmepm8-UR1Hsz86IvSB3KLACMNtX", 
      "type": "master", 
      "id": 321212}, 
  {"status": "Accepted", 
      "stats": {"community": 
          {"in_collection": 448, 
          "in_wantlist": 970}}, 
      "thumb": "", 
      "title": "A View From Slussen", 
      "format": "12\"", 
      "label": "Svek", 
      "role": "Main", 
      "year": 1998, 
      "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
      "artist": "The Persuader", 
      "type": "release", 
      "id": 400}, 
      {"stats": 
          {"community": 
              {"in_collection": 433, 
              "in_wantlist": 841}}, 
          "thumb": "", 
          "artist": "The Persuader", 
          "main_release": 79, 
          "title": "City Of Islands", 
          "role": "Main", 
          "year": 1998, 
          "resource_url": "https://cdnb.artstation.com/p/assets/images/images/015/306/273/large/holo-moon-album-cover2.jpg?1547853203", 
          "type": "master", 
          "id": 4242}, 
      {"stats": 
          {"community": 
              {"in_collection": 396, 
              "in_wantlist": 481}}, 
          "thumb": "", 
          "artist": "Stephan Grieder & The Persuader", 
          "main_release": 401, 
          "title": "Pleasure", 
          "role": "Main", 
          "year": 1998, 
          "resource_url": "https://imagescdn.juno.co.uk/full/IS294749-01-01-BIG.jpg", 
          "type": "master", 
          "id": 4250}, 
      {"stats": 
          {"community": 
              {"in_collection": 436, 
              "in_wantlist": 674}}, 
          "thumb": "", 
          "artist": "The Persuader", 
          "main_release": 101, 
          "title": "Morgon Sol", 
          "role": "Main", 
          "year": 1998, 
          "resource_url": "https://img.discogs.com/9cBHwkiyOApXbswtfpiIFBcRylY=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9121553-1475148661-7202.jpeg.jpg", 
          "type": "master", 
          "id": 374577}, 
  {"status": "Accepted", 
      "stats": 
          {"community": 
              {"in_collection": 185, 
              "in_wantlist": 164}}, 
          "thumb": "", 
          "title": "Stockholm", 
          "format": "CD, Album", 
          "label": "Svek", 
          "role": "Main", 
          "year": 1999, 
          "resource_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXP05me80mcWKN5wijCvhdAmepm8-UR1Hsz86IvSB3KLACMNtX", 
          "artist": "The Persuader", 
          "type": "release", "id": 24200}, 
      {"stats": 
          {"community": 
              {"in_collection": 555, 
              "in_wantlist": 813}}, 
          "thumb": "", 
          "artist": "The Persuader", 
          "main_release": 1, 
          "title": "Stockholm", 
          "role": "Main", 
          "year": 1999, 
          "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
          "type": "master", 
          "id": 1660109}, 
  {"status": "Accepted", 
      "stats": 
          {"community": 
              {"in_collection": 337, 
              "in_wantlist": 248}}, 
          "thumb": "", 
          "title": "Central Bron", 
          "format": "12\"", 
          "label": "Svek, Svek", 
          "role": "Main", 
          "year": 2001, 
          "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
          "artist": "The Persuader", 
          "type": "release", 
          "id": 12362}, 
      {"stats": 
          {"community": 
              {"in_collection": 202, 
              "in_wantlist": 196}}, 
              "thumb": "", 
              "artist": "The Persuader", 
              "main_release": 5226920, 
              "title": "Autumn Leaves EP", 
              "role": "Main", 
              "year": 2013, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "type": "master", 
              "id": 863513}, 
          {"stats": 
              {"community": 
                  {"in_collection": 237, 
                  "in_wantlist": 149}}, 
                  "thumb": "", 
                  "artist": "The Persuader", 
                  "main_release": 5244594, 
                  "title": "Fusion Of Thoughts", 
                  "role": "Main", 
                  "year": 2013, 
                  "resource_url": "https://imagescdn.juno.co.uk/full/IS294749-01-01-BIG.jpg", 
                  "type": "master", 
                  "id": 637047}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 293, 
                  "in_wantlist": 253}}, 
              "thumb": "", 
              "title": "The Persuader EP1", 
              "format": "12\", EP", 
              "label": "Templar (3)", 
              "role": "Main", 
              "year": 2014, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "artist": "The Persuader", 
              "type": "release", 
              "id": 5516176}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 195, 
                  "in_wantlist": 140}}, 
              "thumb": "", 
              "title": "The Persuader EP2", 
              "format": "12\", EP", 
              "label": "Templar (3)", 
              "role": "Main", 
              "year": 2014, 
              "resource_url": "https://imagescdn.juno.co.uk/full/IS294749-01-01-BIG.jpg", 
              "artist": "The Persuader", 
              "type": "release", 
              "id": 5841765}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 306, 
                  "in_wantlist": 241}}, 
              "thumb": "", 
              "title": "The Persuader EP3", 
              "format": "12\", EP", 
              "label": "Templar (3)", 
              "role": "Main", 
              "year": 2014, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "artist": "The Persuader", 
              "type": "release", 
              "id": 6146433}, 
          {"stats": 
              {"community": 
                  {"in_collection": 20, 
                  "in_wantlist": 49}}, 
              "thumb": "", 
              "artist": "The Persuader", 
              "main_release": 6793647, 
              "title": "Skargard", 
              "role": "Main", 
              "year": 2015, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "type": "master", 
              "id": 827783}, 
          {"stats": 
              {"community": 
                  {"in_collection": 278, 
                  "in_wantlist": 329}}, 
              "thumb": "", 
              "artist": "The Persuader", 
              "main_release": 7397291, 
              "title": "V\u00e5rblommor", 
              "role": "Main", 
              "year": 2015, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "type": "master", 
              "id": 926124}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 145, 
                  "in_wantlist": 99}}, 
              "thumb": "", 
              "title": "Himmel R\u00f6d", 
              "format": "12\"", 
              "label": "Parabel", 
              "role": "Main", 
              "year": 2016, 
              "resource_url": "https://img.discogs.com/9cBHwkiyOApXbswtfpiIFBcRylY=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9121553-1475148661-7202.jpeg.jpg", 
              "artist": "The Persuader", 
              "type": "release", 
              "id": 8296032}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 89, 
                  "in_wantlist": 46}}, 
              "thumb": "", 
              "title": "Arrival", 
              "format": "12\"", 
              "label": "Parabel", 
              "role": "Main", 
              "year": 2017, 
              "resource_url": "https://imagescdn.juno.co.uk/full/IS294749-01-01-BIG.jpg", 
              "artist": "The Persuader", 
              "type": "release", 
              "id": 10392503}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 44, 
                  "in_wantlist": 37}}, 
              "thumb": "", 
              "title": "Aftermath", 
              "format": "12\"", 
              "label": "Stockholm LTD", 
              "role": "Main", 
              "year": 2017, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "artist": "The Persuader & Nima Khak", 
              "type": "release", 
              "id": 11334732}, 
      {"status": "Accepted", 
          "stats": 
              {"community": 
                  {"in_collection": 3, 
                  "in_wantlist": 3}}, 
              "thumb": "", 
              "title": "The Kosmos EP", 
              "format": "3xFile, MP3, EP", 
              "label": "Strange Idols", 
              "role": "Main", 
              "year": 2017, 
              "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
              "artist": "The Persuader", 
              "type": "release", 
              "id": 12855756}, 
          {"status": "Accepted", 
              "stats": 
                  {"community": 
                      {"in_collection": 68, 
                      "in_wantlist": 33}}, 
                  "thumb": "", 
                  "title": "Cosmic Isolation EP", 
                  "format": "12\", EP, Ltd", 
                  "label": "Kalvaberget Records", 
                  "role": "Main", 
                  "year": 2019, 
                  "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
                  "artist": "AD* & The Persuader", 
                  "type": "release", 
                  "id": 13392912}, 
              {"stats": 
                  {"community": 
                      {"in_collection": 164, 
                      "in_wantlist": 511}}, 
                  "thumb": "", 
                  "artist": "Superlova", 
                  "main_release": 88892, 
                  "title": "Loves You All Night And Day", 
                  "role": "Remix", 
                  "year": 1997, 
                  "resource_url": "https://images.theconversation.com/files/258026/original/file-20190208-174861-nms2kt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", 
                  "type": "master", 
                  "id": 1157881}, 
              {"stats": 
                  {"community": 
                      {"in_collection": 349, 
                      "in_wantlist": 242}}, 
                  "thumb": "", 
                  "artist": "Dr. Nobody", 
                  "main_release": 119, "title": "The Big Bang Theory", 
                  "role": "Remix", "year": 1997, 
                  "resource_url": "https://f4.bcbits.com/img/a0933471825_16.jpg", 
                  "type": "master", 
                  "id": 169563}
]

export default releases;
